### ISSUE TITLE
Get your .gitconfig together

### ISSUE THREAD

**Issue by jgkamat** [MiningMarsh/pwd#1]
I know eternal root user is amazing, but you can't blame eternal root.

**Comment by MiningMarsh** [comment]
What now? You realize this repo is auto-generated by a tool, right?

**Comment by jgkamat** [comment]
root -> eternalroot or
root -> MiningMarsh or
root -> georgeburdell

**Comment by MiningMarsh** [comment]
What the fuck are you on about?

**Comment by jgkamat** [comment]
![map59](https://cloud.githubusercontent.com/assets/4349709/9563796/cf959dec-4e5d-11e5-9650-971ec694012a.png)

**Comment by jgkamat** [comment]
nevermind lol
it dosent matter

**Comment by MiningMarsh** [comment]
Oh. I can't modify the gitconfig that the android app is using

**Comment by MiningMarsh** [comment]
Once again, auto generated by a tool :P

**Comment by jgkamat** [comment]
nooooooooo
why does it choose root though :open_mouth:

**Comment by MiningMarsh** [comment]
To annoy you, Jay.

**Comment by jgkamat** [comment]
[heh](http://gigjets.com/wp-content/uploads/2012/12/Facebook-Poke-App.jpg)

**Comment by MiningMarsh** [comment]
If you can extract any of the passwords from this repo, I will give you a cookie.

**Comment by MiningMarsh** [comment]
I think I should be fine, they are 4096 keylength GPG keys
